verify binary in pkg verification (#1919)

diff --git a/.github/workflows/package_verification.yml b/.github/workflows/package_verification.yml
--- a/.github/workflows/package_verification.yml
+++ b/.github/workflows/package_verification.yml
@@ -189,7 +189,14 @@ jobs:
         id: verification
         run: |
           composer require statsig/statsig-php-core:${{ matrix.tag == 'beta' && 'dev-main' || '@stable' }}
-          composer install
+          # Capture composer install output
+          output=$(composer install 2>&1)
+          echo "$output"
+          # Check for the verification success string
+          if ! echo "$output" | grep -q "FFI binary verification is successful"; then
+            echo "❌ php binary verification failed"
+            exit 1
+          fi
           php verify.php
 
       - uses: ./.github/actions/log-package-verification-to-statsig
